### ISSUE TITLE
Any working sample to showcase your overlay implementation ?

### ISSUE THREAD

**Issue by tariq235** [gaebel/scanner-overlay#1]
I am trying to capture only AVCaptureVideoPreviewLayer instead of full screen but still unable to do it with the provided details on ReadMe. Can you create a sample app to showcase your overlay implementation ?

**Comment by gaebel** [comment]
If you're using Autolayout you should set the frame of the preview layer in viewDidLayoutSubviews so that you get the correct frame and position (In case you don't want your scanner full screen). If you want to limit scanning to the masked area you have to set the rectOfInterest of your metadataoutput.

For reference I've updated the repo with a small [demo app](https://github.com/gaebel/scanner-overlay/tree/master/Sources/Demo).
